on: workflow_dispatch
name: deploy
jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache Gradle chaches
      uses: actions/cache@v2
      env:
        cache-name: cache-gradle-user-home
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-${{ hashFiles('**/*.gradle.kts') }}
        restore-keys: |
          ${{ runner.os }}-${{ hashFiles('**/*.gradle.kts') }}
          ${{ runner.os }}-
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Gradle Build
      run: "./gradlew app:installDist --scan"
    - name: Docker Build & Push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: blindpirate/qqbot:latest
