on: workflow_dispatch
name: deploy
jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache Gradle chaches
      uses: actions/cache@v2
      env:
        cache-name: cache-gradle-user-home
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-${{ hashFiles('**/*.gradle.kts') }}
        restore-keys: |
          ${{ runner.os }}-${{ hashFiles('**/*.gradle.kts') }}
          ${{ runner.os }}-
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Gradle Build
      run: "./gradlew app:installDist --scan"
    - name: Docker Build & Push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: app
        push: true
        tags: blindpirate/qqbot:latest
    - name: Deploy to EKS
      run: >
        docker run --rm
        -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        -e AWS_DEFAULT_REGION=ap-northeast-2
        jshimko/kube-tools-aws
        bash -c 'aws eks update-kubeconfig --name bytelegend-production && kubectl rollout restart deployment qqbot-app -n production'

